name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        nimversion:
          - binary:stable

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Nim
      uses: iffy/install-nim@v4
      with:
        version: ${{ matrix.nimversion }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run unit tests
      run: |
        nim c -r --hints:off tests/test_main.nim